# Also change hostname_ in cah.js - bjm
# application: google.com:aju-cah-test
# application: brettmorgan-gwt-gadget-test
application: cah-xhack
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.application

libraries:
- name: webob
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

builtins:
- deferred: on

inbound_services:
- channel_presence

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (webapp2\.py)|
 (jinja2/.*)|
 )$