application: cah-xhack
version: 1
runtime: python27
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.application

libraries:
- name: webob
  version: latest
- name: jinja2
  version: latest

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (webapp2\.py)|
 (jinja2/.*)|
 )$