questions = [
  "____________? There's an app for that.",
  "Why can't I sleep at night?",
  "What's that smell?",
  "I got 99 problems but ____________ ain't one.",
  "Who stole the cookies from the cookie jar?",
  "What's the next Happy Meal toy?",
  "Anthropologists have recently discovered a primitive tribe that worships ____________.",
  "It's a pity that kids these days are all getting involved with ____________.",
  "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ____________.",
  "Alternative medicine is now embracing the curative powers of ____________.",
  "What's that sound?",
  "What ended my last relationship?",
  "MTV's new reality show features eight washed-up celebrities living with ____________.",
  "I drink to forget ____________.",
  "I'm sorry professor, I couldn't complete my homework because of ____________.",
]

answers = [
  "Coat hanger abortions.",
  "Man meat.",
  "Autocannibilism.",
  "Vigorous jazz hands.",
  "Flightless birds.",
  "Pictures of boobs.",
  "Doing the right thing.",
  "Hunting accidents.",
  "A cartoon camel enjoying the smooth, refreshing taste of a cigarette.",
  "The violation of our most basic human rights.",
  "Viagra.",
  "Self-loathing.",
  "Spectacular abs.",
  "An honest cop with nothing left to lose.",
  "Abstinence.",
  "A balanced breakfast.",
  "Mountain Dew Code Red.",
  "Concealing a boner.",
  "Roofies.",
  "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.",
  "Tweeting.",
  "The big bang.",
  "Amputees.",
  "Dr. Martin Luther King, Jr.",
  "Former President George W. Bush.",
  "Being marginalized.",
  "Smegma.",
  "Laying an egg.",
  "Cuddling.",
  "Aaron Burr.",
  "The Pope.",
  "A bleached asshole.",
  "Horse meat.",
  "Genital piercings.",
  "Fingering.",
  "Elderly Japanese men.",
  "Stranger danger.",
  "Fear itself.",
  "Science.",
  "Praying the gay away.",
  "Same-sex ice dancing.",
  "The terrorists.",
  "Making sex at her.",
  "German dungeon porn.",
  "Bingeing and purging.",
  "Ethnic cleansing.",
  "Cheating in the Special Olympics.",
  "Nickelback.",
  "Heteronormativity.",
]
